### ISSUE TITLE
Consider `after styles` and `after scripts` hooks

### ISSUE THREAD

**Issue by necolas** [componentjs/builder.js#147]
One of the examples given is using Rework to transform the CSS with a `before styles` hook. Should there be `after styles` and `after scripts` too (akin to npm's `postpublish`)?

For example, if you're using variables in your CSS, then you're likely to want to resolve them once you have all the external and local components assembled. Although, I'm aware that this step can be done outside of running component.

**Comment by tj** [comment]
I was actually just talking to @yields last night about redoing builder, I was in a hurry initially so it's pretty damn brutal haha, but we were thinking of making it much more rework-like. We need to pre-compute a dep tree for a few things anyway, so we were thinking if we pulled in all the source and attached that to the tree, people could just write plugins that arbitrarily add/remove/edit source just by walking the tree and doing whatever they want. One of our use-cases is that we need to dynamically filter out modules and produce a build specific to one client's needs, so that would be much easier with this setup as well

**Comment by necolas** [comment]
That sounds great!

> One of our use-cases is that we need to dynamically filter out modules and produce a build specific to one client's needs

Do you have a specific example of what you mean?

**Comment by yields** [comment]
@visionmedia 

i got the tree working in [rework](https://github.com/yields/builder.js/tree/rework) branch, i'm thinking on moving it to `component/tree` or something.

it basically just resolves components that were already downloaded, fetches their `component.json` pulls some sources `(templates, scripts etc..)` and provides the root component.

hopefully the new builder will just accept the root component and can use plugins to manipulate stuff then stringify and write.

let me know if you like it so i can move it to `component/tree` ? :D

**Comment by jonathanong** [comment]
hah. i worked on https://github.com/component/resolve-locals.js and will be doing resolve-dependencies.js next. was going to wait, but you guys seem to really want this so i'll do it this weekend. it'll have some validations for the new spec, semver, etc.

i'm not sure what the point of a "tree" actually is, though. component will flatten out all the components and order does matter, so a tree won't make it much easier. all you need is a reference to the "resolved" dep on each component IMO. 

my goal is to create a flat list of deps and a flat list of locals, and all the builder would have to do would be like:

``` js
var css = components.map(function (component) {
  var styles = component.styles
  if (!styles) return '';
  return styles.map(function (filename) {
    return fs.readFileSync(path.resolve(component.filename, filename), 'utf8')
  }).join('')
}).join('')
```

for the CSS, but async. thus, separate builders for different types of stuff since CSS would be the easiest. 

we can also do cooler things like only build the local components or only build the deps, rebuild without re-resolving, etc.

**Comment by tj** [comment]
yeah it doesn't have to actually be a deep tree, as long as you can get to the other packages, same thnig

**Comment by ericgj** [comment]
The direction this is going seems pretty murky ATM but @yields I like your component/tree, would love to help out adding some test cases if that's the way we're going.

**Comment by tj** [comment]
what's murky about rewriting :p

**Comment by ericgj** [comment]
haha - what's not?  what I meant was it seems this component/tree and component/resolve-locals seem to aim to provide overlapping things to the builder so not clear how they fit together.

**Comment by jonathanong** [comment]
they're the same thing really. difference is that resolve returns the tree flattened and attaches stuff to the component.jsons. also, it only handled locals.

**Comment by yields** [comment]
666040ac9bc2cc0c031b6e70f5de97ff73c62d79
