### ISSUE TITLE
Allow omitting "main" when component contains single script

### ISSUE THREAD

**Issue by karlbohlmark** [componentjs/builder.js#34]
When writing a component with a single script in "scripts", it feels unnecessary to add a "main" directive to point to it.

**Comment by karlbohlmark** [comment]
Well, maybe I take that back. It might be better to leave this requirement as it is. Being explicit has pedagogical advantages. However I'd like to know the reasoning behind recommending the main script to be called index.js. To me it seems this has drawbacks when looking up the file in dev tools/your editor and no obvious advantages (besides making it easy to determine which file is 'main' when looking at the directory of a component)

**Comment by tj** [comment]
yeah it would be just as easy to have no default at all, though the searching part is really just editors having poor search IMO. Otherwise the only way you'll have unique names is if you have gigantic java-style filenames, which is also not really ideal. A good search is a fuzzy search with dirname included. In general I just favour simplicity over minor conveniences like this, because then next thing you know, you have globbing of files and a lot of other odd complexity that isn't really necessary

**Comment by jonathanong** [comment]
i think we should support this just for robustness, but if/when we have a registry, we should warn if `main` is not defined and `scripts[0]` isn't `index.js`.

**Comment by jonathanong** [comment]
migrating to https://github.com/component/spec/issues/28
