### ISSUE TITLE
fs.readFile() request for component.json being called twice

### ISSUE THREAD

**Issue by wilsonpage** [componentjs/builder.js#60]
The first time `Builder.prototype.buildType` method is run it is for 'scripts' and an async request for the component.json config request is made. Then `Builder.prototype.buildType` is run again  for 'styles'. The callback for the first request has not returned, and therefore not been cached, so a second request is made for the component.json is made.

This is problematic, as it is possible that two completely different instances of the configuration could be floating around.

I believe this to be cause of a problem I had doing async stuff inside a 'styles' hook. I hope I have got this right.

This gist shows an example:
https://gist.github.com/4556128

**Comment by wilsonpage** [comment]
Ok think I've got the problem now.

When the request to `Builder.prototype.buildType` is made, it requests the component.json. This triggers an async call for the file contents. The callback is fired passing the `conf` json. The `before` hook is then triggered activating any assigned callbacks. Before the async `before` hook callback is run, other async callbacks for the component.json return, creating new instances of `conf`.

In my before hook I attach fabricated files to the `conf`. When I have finished the before hook, I call the callback. Inside the callback (ln 578) Builder checks for files of that type in the `conf`, but the `conf` being checked is a different instance to the one I added my files to, meaning the new fabricated files I just added are not found, and not added to the end build package. Few!

Ensuring the request for the `component.json` only made once should fix this problem. All subsequent requests must feed from the cache.

Does this make sense?

**Comment by tj** [comment]
there's quite a bit of caching that could be added, I actually had it all implemented and somehow lost my branch :( but I had the builder about %400 faster. Just need to go back and add it, the difficulty there is having a big enough test app set up to properly benchmark things, and remember everything I changed :D 

I definitely changed the async config loading to sync though, not only does it simply code it sped things up a lot. It gets a little tricky too because we need Builder#build() to be idempotent, since ideally in middleware you do `new Builder` only once in the closure so that the config JSON and a few other things can be perma-cached, speeding things up further. I dont like having that much state in the object though, I think it may be nicer to have some Cache environment object that we toss in instead

**Comment by wilsonpage** [comment]
Damn that's such a bugger you lost that branch :( I'm trying to put together an example app of my own, compiling SASS and Hogan templates inside before hooks. I have made a couple of changes to work around this Builder issue.

At line 578:

```
if (conf[type]) {
  conf[type].forEach(function(file){
```

Becomes

```
if (self.conf[type]) {
  self.conf[type].forEach(function(file){
```

This seems to be quick fix to ensure new fabricated files created asynchronously exist on the `conf` object. But I think changing to `readFIleSync` should fix this too. 

Any plans to re-implement that lost work?

**Comment by tj** [comment]
yeah I definitely plan to, the json thing first, I'll take the todo app and exaggerate it or something to get a better idea for perf

**Comment by tj** [comment]
changed it to sync
